services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5433/everydai_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: everydai_db
    ports:
      - "5433:5432"

  documentation:
    image: nginx:alpine
    volumes:
      - ./documentation:/usr/share/nginx/html
    ports:
      - "8080:80"
